/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _PrismaMigrations {
  applied_steps_count: Generated<number>;
  checksum: string;
  finished_at: Timestamp | null;
  id: string;
  logs: string | null;
  migration_name: string;
  rolled_back_at: Timestamp | null;
  started_at: Generated<Timestamp>;
}

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Project {
  archived: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: string;
  metadata: Json | null;
  name: string;
  ownerId: string;
  slug: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface ProjectManager {
  createdAt: Generated<Timestamp>;
  projectId: string;
  terminatedAt: Timestamp | null;
  userId: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  banExpires: Timestamp | null;
  banned: Generated<boolean>;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  role: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  _prisma_migrations: _PrismaMigrations;
  account: Account;
  project: Project;
  project_manager: ProjectManager;
  session: Session;
  user: User;
  verification: Verification;
}
