import { Box, Button, Group, Input, Text } from "@mantine/core";
import { Pencil, RotateCcw } from "lucide-react";
import { useState } from "react";
import { slugify } from "~/lib/admin/types";

interface ProjectSlugInputProps {
  name: string;
  slug: string;
  onSlugChange: (slug: string) => void;
}

export function ProjectSlugInput({
  name,
  slug,
  onSlugChange,
}: ProjectSlugInputProps) {
  const [isEditingSlug, setIsEditingSlug] = useState(false);

  const expectedSlug = slugify(name);
  const isAutoGenerated = slug === expectedSlug;

  const handleButtonClick = () => {
    if (isEditingSlug) {
      onSlugChange(expectedSlug);
      setIsEditingSlug(false);
    } else {
      setIsEditingSlug(true);
    }
  };

  return (
    <Box>
      <Group gap="xs" mb={4}>
        <Text size="sm" fw={500}>
          URL Slug
        </Text>
        <Text size="xs" c={isAutoGenerated ? "green" : "red"} fw={600}>
          {isAutoGenerated
            ? "Auto-generated"
            : "URL slug does not match project name"}
        </Text>
      </Group>
      <Group gap="xs">
        <Text size="sm" c="dimmed">
          /project/
        </Text>
        <Input
          aria-label="Project URL slug"
          value={slug}
          onChange={(e) => onSlugChange(e.currentTarget.value)}
          className="flex-1"
          disabled={!isEditingSlug}
        />
        <Button
          variant="default"
          size="xs"
          onClick={handleButtonClick}
          leftSection={
            isEditingSlug ? <RotateCcw size={14} /> : <Pencil size={14} />
          }
        >
          {isEditingSlug ? "Reset" : "Edit"}
        </Button>
      </Group>
      <Text size="xs" c="dimmed" mt={4}>
        Project URL: /project/{slug}
      </Text>
      <input type="hidden" name="slug" value={slug} />
    </Box>
  );
}
